### ISSUE TITLE
`resolve(..)` should call a thenable's `then(..)` async, not sync.

### ISSUE THREAD

**Issue by getify** [getify/native-promise-only#45]
This isn't a A+ requirement, it's an [ES6 requirement](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-promiseresolvethenablejob).

The problem is, when I "fix" this, it causes lots of other test failures. And also the A+ test suite failures are intermittently different on each run, and sometimes the runner itself crashes. So, basically, this is impossible to track down.

This may in fact be a bug in not adhering to the ES6 spec, but I don't expect to be able to fix it, at least not any time soon. Spent a whole day on it so far, and failed. That's more time than I have to devote to such things.

More info: https://github.com/zloirock/core-js/issues/78

For posterity, these are the offending lines, I believe:

https://github.com/getify/native-promise-only/blob/e18a8de53fce80c0b7a4176dee2a12edce73fd90/lib/npo.src.js#L155-L158

I believe that call is supposed to be deferred (with `schedule(..)`), but that breaks everything.

**Comment by Octane** [comment]
I don't understand what the problem to call a thenable's then asynchronously.
In [my implementation](https://github.com/Octane/Promise) a thenable's then [always will be called asynchronously](https://github.com/Octane/Promise/blob/master/promise.js#L104-L110), and it passing the Promise/A+ test suite.

Also with thenables there is [another interesting issue](https://github.com/promises-aplus/promises-spec/issues/193).

**Comment by zloirock** [comment]
@Octane your issue looks similar mentioned, see where V8 get `.then` https://github.com/zloirock/core-js/issues/78#issuecomment-110226792

**Comment by getify** [comment]
> I don't understand what the problem to call a thenable's then asynchronously.

The issue here is that NPO currently passes Promises/A+ when calling `then(..)` synchronously, but when I call it asynchronously, NPO has like 70+ test failures. I don't know why. I spent a day trying to figure it out, and failed.

**Comment by zloirock** [comment]
@getify see https://github.com/zloirock/core-js/commit/17300b01cdc9cea04cee1a23b5d38d4fe2f3bb5d , NPO with same fix passes Promises/A+ test case. I can add PR.

**Comment by getify** [comment]
<3 <3 Huge thanks @zloirock!
