### ISSUE TITLE
Unhandled rejection detection

### ISSUE THREAD

**Issue by benjamingr** [getify/native-promise-only#47]
This is a much much less argumentative idea than the last discussion we've had about it here. 

[Promise Unhandled Rejection Hook](https://gist.github.com/benjamingr/0237932cee84712951a2)

CoreJS does this using native promises only as the base. In addition native promises do this in io.js and NodeJS (soon) and this would be required to remain complaint to the spec in io.js. Most promise libraries (Q, Bluebird, When, lie etc) have already implemented this.

Cheers!

**Comment by getify** [comment]
I would happily consider a PR for this. ;-)

**Comment by OliverJAsh** [comment]
When does this well: https://github.com/cujojs/when/blob/master/docs/debug-api.md#debug-apis

AFAIK this matches the future spec: https://groups.google.com/a/chromium.org/forum/m/#!topic/blink-dev/SRsFwwEgnUQ

**Comment by legodude17** [comment]
Should it emit it globally (on `process` or `window`) or locally (on `Promise`).

**Comment by getify** [comment]
globally I believe

**Comment by legodude17** [comment]
`when` does it globally, and `bluebird` does both. Emitting on `process` is simple but emitting on `window` with the promise in the event seems harder, I have not figured out how to do it. If anyone knows please say. I will be happy to do a PR.

**Comment by legodude17** [comment]
Never mind figured it out. :)

**Comment by legodude17** [comment]
I finished it. One questions: If you create a promise with `Promise.reject(...)` and then call `.then(...)` on it, how many times do you think the event should be emitted? I am thinking one, but the way I build it it is two. Using native promises it is once.

**Comment by legodude17** [comment]
I rewrote it for one. The pull request is waiting: #54.

**Comment by legodude17** [comment]
@getify, can I get your opinion on #54?
