### ISSUE TITLE
Suggestion: make Promise.prototype aliases of `then` and `catch`

### ISSUE THREAD

**Issue by impinball** [getify/native-promise-only#48]
Something like this:

```js
Promise.prototype.then = function () {
  return this.then.apply(this, arguments)
}

Promise.prototype.catch = function () {
  return this.catch.apply(this, arguments)
}
```

Obviously, I don't mean directly assigning, but you know what I mean. :wink:

**Comment by getify** [comment]
What would the value of this change be?

**Comment by impinball** [comment]
Basically, covering an edge case to be closer to the spec.

**Comment by getify** [comment]
What edge case, specifically? IOW, where would you ever care about the presence of these on the `.prototype` unless you were trying to some sort of "subclassing", which specifically this package declares it isn't intended to support?

**Comment by impinball** [comment]
Okay... On that note, I'll retract the suggestion. (I didn't notice that at
first)

**Comment by getify** [comment]
No worries. Cheers. Was sincerely wondering if I was missing something.
