### ISSUE TITLE
Error when running through babel compiler

### ISSUE THREAD

**Issue by alexreardon** [getify/native-promise-only#49]
When `npo.src.js` or `npo.js` is run through babel the following line:

```js
})("Promise", typeof global != "undefined" ? global : this, function DEF() {
```
becomes
```js
})("Promise", typeof global != "undefined" ? global : undefined, function DEF() {
```

This causes this line to die, as context is `undefined`
```js
 // special form of UMD for polyfilling across evironments
      context[name] = context[name] || definition();
```

Script to replicate issue:

```js
var fs = require('fs'),
    babel = require('babel-core');
babel.transformFile('./node_modules/native-promise-only/lib/npo.src.js', function (err, result) {
    if(err) {
        return console.log(err);
    }
    fs.writeFileSync('.temp.txt', result.code, {
        encoding: 'utf8'
    });
});
```

**Comment by zloirock** [comment]
https://babeljs.io/docs/faq/#why-is-this-being-remapped-to-undefined-

Use [correct way detection global object](https://github.com/zloirock/core-js/blob/master/modules/%24.global.js#L1).

**Comment by getify** [comment]
1. Polyfills shouldn't be run through a transpiler. That doesn't make sense. In fact, you shouldn't run any third-party code through a transpiler, IMO. Exclude such file(s) from transpilation runs.
2. I disagree with babel that such assumptions about `this` are either spec compliant or appropriate for polyfills.

Sounds like you should either not run NPO through babel, or you should blacklist the `strict` transformer, as @zloirock suggests.

----

> use correct way detection global object.

I disagree that the much more convoluted code linked to is "correct". It may work, but it's far from what we ought to be doing. See points above.

**Comment by zloirock** [comment]
@getify see [this table](https://github.com/zloirock/core-js/issues/86#issuecomment-115759028). It not contains `this` because of strict mode, but w/o strict mode in many case it shouldn't work too. It's simples correct for most case way, "convoluted", for example, [in LoDash](https://github.com/lodash/lodash/blob/master/lodash.js#L248-L275).

**Comment by alexreardon** [comment]
I agree with your first point @getify. I makes little sense to run a library through babel. I now exclude it. Thanks!

**Comment by getify** [comment]
Cheers!
