### ISSUE TITLE
on nodejs, exceptions are not shown.

### ISSUE THREAD

**Issue by makall** [getify/native-promise-only#51]
hi, i'm using swagger-node, that uses json-refs, that uses your module.

a couple of weeks ago I noticed that at one point of the code the exceptions stopped appear on console. Then, today I tracked this issue and replacing your module by bluebird, the exceptions are shown properly, and returning to your module the exceptions stops shown.

reproducing the problem is easy, just create a swagger project and change the controller file to not "compile"; the program will stop in the initialization and no output will be shown.

**Comment by getify** [comment]
NPO does not currently support the recently "standardized" feature "unhandled promise rejections".

If you always register rejection handlers on every promise, you'll never miss them being notified. If you rely on unhandled promise notifications, I think that's sub-optimal design.

**Comment by solendil** [comment]
Hi,

I agree we shouldn't rely on unhandled promises notifications; yet I have inherited a huge code base where I need to track them, if only to log and fix them. Perhaps do you know if:

- such a thing would be feasible in npo.src.js ?
- are there other polyfills that support this feature ?

Thank you

**Comment by getify** [comment]
It is on my radar to explore support for it. But the decision to support needs to be balanced against size/speed costs it will bring to the polyfill. Since the behavior in question is not standardized, I'm automatically skeptical of if it belongs in a **polyfill**, so honestly the priority of adding it is not high. Were this a promise library, of course it would make much more obvious sense without question.

**Comment by solendil** [comment]
Ooops, my bad. I thought this feature was in the standardisation process, but it seems to exist only in the Whatwg living standard atm. I understand your stance of not wanting to include it in a simple polyfill. 
Let's hope it will get standardized soon. It is such an invaluable feature for debugging.
