### ISSUE TITLE
Missing tag for version 0.7.8-a used by jQuery

### ISSUE THREAD

**Issue by mirabilos** [getify/native-promise-only#57]
jQuery 1.12.4 ships a minified-only npo v0.7.8-a with no source available, which makes jQuery 1.12.4 not Open Source, and not suitable for Debian to boot.

The npo repository does not have a git tag corresponding to v0.7.8-a and does not contain the minified compilation output, so I cannot find out the correct source code myself.

This makes jQuery 1.12.4 non-redistributable under OSS rules.

**Comment by getify** [comment]
Shipping minified code is not in violation of "OSS rules" as far as I'm aware. It's pretty common. I believe they should be shipping it with the copyright notice/license included, though.

I've been unable yet to find this "jquery 1.12.4" distribution that you say includes native-promise-only. Can you link me to where to see it?

**Comment by mirabilos** [comment]
Sure, look at https://github.com/jquery/jquery/tree/1.12.4/external/npo

I’ll answer on the source code issue in https://github.com/jquery/jquery/issues/4445

**Comment by mirabilos** [comment]
The correct commit to tag is probably commit f3cc8e8425e713939d6e3f78b124621dc35628e7 but I cannot get the exact binary they have in the jQuery repo, probably due to a version difference in the minifier (Debian has 3.6.0-3 while your `package.json` mentions 2.4.8 with a tilde(?)), which makes this kinda tricky (and is another good reason for why people ought to always include source code).

**Comment by mirabilos** [comment]
Yes, that is the correct commit. I was able to reproduce it by taking a throwaway system with npm, installing `uglify-js@2.4.8` via npm, then running `(uglifyjs -m -c --comments '/^!/' lib/npo.src.js; echo) >npo.js` on the command line. The result is bytewise identical.

**Comment by getify** [comment]
I don't see any particular reason you're concerned here though? Why should I go back and add an old tag to some old release simply because jQuery chose to use that version (from npm)?

You can see the code here on github, so that's the concern you had, right?

**Comment by mirabilos** [comment]
I can see “some” code, but not the exact correct code. I had to invest a lot of time to figure that out, and others are not as skilled in software archæology.

**Comment by getify** [comment]
It's easy to get the exact code:

```cmd
npm install native-promise-only@0.7.8-a
```

Inside, you'll find the original source code as well as the minified code (not binary) and even the script that did the minification, if you want to recreate it.

I recognize you had some difficulty researching to figure this out, but it seems clear to me everything is resolved now.
