### ISSUE TITLE
Promise finally not supported

### ISSUE THREAD

**Issue by poebrand** [getify/native-promise-only#58]
In IE 11, when running the following code:
`Promise.resolve().then(function(){console.log('hi');}).finally(function(){console.log('victory');});`

It results in the error:
Object doesn't support property or method 'finally'

From looking at the code, it appears that isn't supported. Is that right? If so, any plans to add support?

**Comment by getify** [comment]
NPO adds ES6 promises to pre-ES6 environments that have no promises at all. It's not designed or intended to be a polyfill on top of native promises for further post-ES6 additions to the promise API.

There are a number of polyfill options for recent amendments to promises (like `finally`), which can be used on top of native-promise-only. In the case of `finally`, it's actually quite easy to polyfill in a simple/naive way:

```js
// adapted from: https://gist.github.com/spiralx/58675999ca5b28453538d30859761947
if (!Promise.prototype.finally) {
  Promise.prototype.finally = function finally(callback){
    return this.then(
      value => this.constructor.resolve(callback()).then(() => value),
      reason => this.constructor.resolve(callback()).then(() => { throw reason })
    );
  }
}
```

You could probably just copy-n-paste that snippet in the code bundle where you're already including native-promise-only and I bet it would work fine (haven't tried it myself, tbf).

----

There are other polyfills that are a little bit more robust and strictly spec adherent (for extreme spec nuances) if you're worried about the far corner cases. For example, there's this very popular one: https://www.npmjs.com/package/promise.prototype.finally Note that this one can optionally include a separate polyfill for `Promise`, so you could switch from native-promise-only completely.
